/*
* Created by gsg on 10/02/17.
*/

#ifndef PRESTO_PRESTO_RELEASE_VERSION_H
#define PRESTO_PRESTO_RELEASE_VERSION_H

#define PRESTO_FIRMWARE_VERSION "1.2.9 30-May-2019"

#endif /* PRESTO_PRESTO_RELEASE_VERSION_H */
